In [25]:
import numpy as np

# Problem 1

### Create an array of the cubes of the numbers 1 through 20 using numpy, without manually typing them out yourself hint using np.arange or np.linspace to help you out with this.

np.arrange goes up to 21 because np.arrange stops before reaching the second element inside the "(_)" so by writing 21 the arrange will reach 20. Placing a 1 as a first element makes the range start at 1 instead of 0.

In [26]:
a = np.arange(1,21)
cubed = a**3
cubed

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000, 1331,
       1728, 2197, 2744, 3375, 4096, 4913, 5832, 6859, 8000])

# Problem 2

### The data from this website has both distances from the sun and diameters of planets in our solar system. Create a .csv file to store the data and then read it into your notebook using np.genfromtxt. Create two separate variables dist and diam to handle the data.

the for loop iterates through the Prows list, unpacking each pair into distance (d) and diameter (dd) . Using delimiter to seperate the lines by the commas and skip_header = 1 to skip the first row or esle it wont read the table right or at all lol.

In [27]:
Pnames = ["Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune"]
Prows = [(0.39, 4879),
    (0.72, 12104),
    (1.00, 12742),
    (1.52, 6779),
    (5.20, 139820),
    (9.54, 116460),
    (19.22, 50724),
    (30.06, 49244),]

with open("planet.csv", "w") as f:
    f.write("distance,diameter")
    for d, dd in Prows:
        f.write(f"{d},{dd}\n")
        

In [28]:
d, dd = np.genfromtxt("planets.csv", delimiter=",", skip_header=1, unpack=True)
d, dd

(array([ 0.39,  0.72,  1.  ,  1.52,  5.2 ,  9.54, 19.22, 30.06]),
 array([  4879.,  12104.,  12742.,   6779., 139820., 116460.,  50724.,
         49244.]))

# Problem 3
In order to better grasp the differences in distances, take the log of dist and diam and display the resulting outputs.

In [29]:
log_d = np.log(di)
log_dd = np.log(diam)

print(log_d)
print(log_dd)

[-0.94160854 -0.32850407  0.          0.41871033  1.64865863  2.25549349
  2.9559514   3.40319538]
[ 8.49269556  9.40129126  9.4526589   8.82158488 11.84811116 11.66530315
 10.83415445 10.80454281]


# Problem 4
### Sort the planets by size and by diameter using numpy functions.

This is where Pnames come in handy for the table. using np,argsort to arrange distance by smallest to largest. then used an array to match the smallest to biggets with the pnames column.

In [33]:
order_by_diameter = np.argsort(d)
planets_by_diameter = np.array(Pnames)[order_by_diameter]
print(planets_by_diameter)

['Mercury' 'Venus' 'Earth' 'Mars' 'Jupiter' 'Saturn' 'Uranus' 'Neptune']


# Problem 5 
### Calculate the distance between the orbits of Earth and each other planet.

using an index to locate earth on the list 3rd, we use its distance column against the other distance colums for each planet in the index we us abs to get an absolute number to avoid negative. from the ones before earth. 

In [41]:
E_P = Pnames.index("Earth")
ed = d[E_P]
distanceFromEarth = np.abs(d-ed)
distanceFromEarth

array([ 0.61,  0.28,  0.  ,  0.52,  4.2 ,  8.54, 18.22, 29.06])

# Problem 6 
### Sort the planets by distance from Earth.

using argsort to get smallest to largest obviously eath is 0 so its going to be first. before using np.abs on 5 venus and mars where ahead. this solves that problem.

In [42]:
order_by_Distance = np.argsort(distanceFromEarth)
Final_order = np.array(Pnames)[order_by_Distance]
Final_order

array(['Earth', 'Venus', 'Mars', 'Mercury', 'Jupiter', 'Saturn', 'Uranus',
       'Neptune'], dtype='<U7')

# AI Acknowledgement Statement

Please indicate if and how you used ChatGPT or other LLMs on this assignment. Use the option that best fits your use case:

* [x] I did not use ChatGPT/LLMs.
* [ ] I consulted ChatGPT/LLMs (to brainstorm, to debug, to get information, to give feedback), but I did not copy and paste or use text directly from ChatGPT/LLMs.
* [ ] I copied and pasted portions of code directly from ChatGPT/LLMs.
* [x] I consulted other outside sources other than ChatGPT/LLMs.
      

Please provide any and all links to ChatGPT/LLM conversations or other sources used in this assignment and describe how they were used:

| Problem          | Link                                     | Description                                   |
|------------------|------------------------------------------|-----------------------------------------------|
|HW_01                | https://www.dataquest.io/cheat-sheet/numpy-cheat-sheet/ | I used this cheat sheet as a reference. |
| &nbsp;           | &nbsp;                                  | &nbsp;                                       |
| &nbsp;           | &nbsp;                                  | &nbsp;                                       |
| &nbsp;           | &nbsp;                                  | &nbsp;                                       |