CS238, 8/27/26, shell commands, version controls & numpy

In [2]:
import numpy as np


In [7]:
temps = [110, 105, 101, 103]

avg = 0
for temp in temps: 
    avg+= temp/4

In [10]:
avg

104.75

In [15]:
tempsA = np.array(temps)
print("A")

A


In [16]:
2.5*tempsA

array([275. , 262.5, 252.5, 257.5])

In [18]:
np.log(tempsA)

array([4.70048037, 4.65396035, 4.61512052, 4.63472899])

In [19]:
np.average(tempsA)

np.float64(104.75)

In [20]:
days = np.array([1, 2, 3, 4])


In [21]:
days

array([1, 2, 3, 4])

In [22]:
type(days)

numpy.ndarray

In [23]:
days.dtype

dtype('int64')

In [24]:
np.version

<module 'numpy.version' from 'C:\\Users\\edwin\\anaconda3\\Lib\\site-packages\\numpy\\version.py'>

In [25]:
np.version.version

'2.3.5'

In [26]:
days + tempsA

array([111, 107, 104, 107])

# AI Acknowledgement

- [X] By checking this box and signing my name below, I acknowledge that no portion of this assignment was generated with ChatGPT or other AI/LLM services.

- **Signature**: Edwin Acosta

no notes for today.

add ccurti7 as colaborator.