CS238, 8/27/26, shell commands, version controls & numpy

In [4]:
import numpy as np


the for loop starts a variable avg at 0, then for every value in temps, it adds temp/4 to avg. Since there are exactly four values, dividing each one by 4 before adding it up is the same as adding all four values and then dividing the total by 4 to get the average.


In [5]:
temps = [110, 105, 101, 103]

avg = 0
for temp in temps: 
    avg+= temp/4

In [6]:
avg

104.75

np.array(temps) takes our Python list temps and converts it into a nummpy ndarray.numpies arrays behave very differently for example: multiplication, addition, and math functions apply to every element at once. replacing the for loop to fo the math.

In [9]:
tempsA = np.array(temps)
print("A")

A


In [10]:
2.5*tempsA

array([275. , 262.5, 252.5, 257.5])

In [11]:
np.log(tempsA)

array([4.70048037, 4.65396035, 4.61512052, 4.63472899])

In [12]:
np.average(tempsA)

np.float64(104.75)

In [13]:
days = np.array([1, 2, 3, 4])


In [14]:
days

array([1, 2, 3, 4])

type(days) confirms that days is a numpy.ndarray. type() can be used to check when you're not sure what kind of object you're working with or you want to make sure you are using nuumpy since lists and numoy arrays have different limits to what you can do with them.

In [15]:
type(days)

numpy.ndarray

.dtype will till you if its a float, or integer d probably stand or data for data type all together so when doing computation you don't accidently put a float against an int expecting and int. 

In [16]:
days.dtype

dtype('int64')

version check / version control. some older version won't work with newer packages so its important to check

In [24]:
np.version

<module 'numpy.version' from 'C:\\Users\\edwin\\anaconda3\\Lib\\site-packages\\numpy\\version.py'>

In [25]:
np.version.version

'2.3.5'

In [26]:
days + tempsA

array([111, 107, 104, 107])

# AI Acknowledgement

- [X] By checking this box and signing my name below, I acknowledge that no portion of this assignment was generated with ChatGPT or other AI/LLM services.

- **Signature**: Edwin Acosta

no notes for today.

add ccurti7 as colaborator.